### PR TITLE
Switch to faustwasm, reorganize

### PR DESCRIPTION
**Pull request by ijc8**
Starting from #7: rebase onto `master`, avoid checking in a copy of faustwasm, convert source files to modules, improve type-checking.

### CODE REVIEW

**Comment by sletz** [comment]
Thanks, somewhat working with some issues:
- in build mode (`npm run build`), I get this error:
```
FaustPlayground: version 1.1.0 (2023-07-04)
index-e2352b31.js:32 Module {…}
index-e2352b31.js:1 enter onreadystatechange
3index-e2352b31.js:1 enter onreadystatechange
index-e2352b31.js:32 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
it @ index-e2352b31.js:32
loadMessages @ index-e2352b31.js:32
(anonymous) @ index-e2352b31.js:32
i.onreadystatechange @ index-e2352b31.js:1
XMLHttpRequest.send (async)
getXHR @ index-e2352b31.js:1
getResources @ index-e2352b31.js:32
tt @ index-e2352b31.js:32
await in tt (async)
(anonymous) @ index-e2352b31.js:32
8[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
index-e2352b31.js:32 Uncaught ReferenceError: Ps is not defined
    at ze.initLibraryView (index-e2352b31.js:32:33474)
    at Ke.init (index-e2352b31.js:32:43776)
    at new _e (index-e2352b31.js:32:44768)
    at qe.createMenu (index-e2352b31.js:32:57033)
    at it (index-e2352b31.js:32:75302)
    at Q.loadMessages (index-e2352b31.js:32:74430)
    at index-e2352b31.js:32:74283
    at i.onreadystatechange (index-e2352b31.js:1:2015)
initLibraryView @ index-e2352b31.js:32
init @ index-e2352b31.js:32
_e @ index-e2352b31.js:32
createMenu @ index-e2352b31.js:32
it @ index-e2352b31.js:32
loadMessages @ index-e2352b31.js:32
(anonymous) @ index-e2352b31.js:32
i.onreadystatechange @ index-e2352b31.js:1
XMLHttpRequest.send (async)
getXHR @ index-e2352b31.js:1
getResources @ index-e2352b31.js:32
tt @ index-e2352b31.js:32
await in tt (async)
(anonymous) @ index-e2352b31.js:32
index-e2352b31.js:32 timeIn
index-e2352b31.js:32 audio track has settings: {autoGainControl: false, channelCount: 1, deviceId: 'aa98010340604c91d549544e7703bb508229f9e248de746a88a844b7ccf4d197', echoCancellation: false, groupId: 'd6117ecaa58bdb78422c6de48624f9cc029009a0d68d8694014c460f37cb8968', …}
index-e2352b31.js:32 timeout
```
- in dev mode (`npm run dev`), I get this error when exporting: 
```
client.ts:18 [vite] connecting...
client.ts:133 [vite] connected.
Main.ts:36 FaustPlayground: version 1.1.0 (2023-07-04)
Main.ts:39 Module
Utilitary.ts:52 enter onreadystatechange
3Utilitary.ts:52 enter onreadystatechange
Main.ts:63 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
resumeInit @ Main.ts:63
loadMessages @ Resources.ts:113
(anonymous) @ Resources.ts:105
getrequest.onreadystatechange @ Utilitary.ts:54
Utilitary.ts:52 enter onreadystatechange
Utilitary.ts:52 enter onreadystatechange
3Utilitary.ts:52 enter onreadystatechange
SceneClass.ts:69 timeIn
SceneClass.ts:180 audio track has settings: Object
3Utilitary.ts:52 enter onreadystatechange
SceneClass.ts:74 timeout
Export.ts:125 Uncaught ReferenceError: ExportLib is not defined
    at _Export.exportPatch (Export.ts:125:9)
    at HTMLInputElement.eventExport (Export.ts:27:46) 
```

**Comment by sletz** [comment]
Works correctly AFAICS, some questions:
- what is `vite` tool used for? Building the dev version ? release version?
- is the "To rebuild the JavaScript" section in README.md still valid?

**Comment by ijc8** [comment]
@sletz
>  * what is `vite` tool used for? Building the dev version ? release version?

It's used for both dev and production, as with grame-cncm/fausteditor#4 (and like webpack is currently used in grame-cncm/faustide).
> * is the "To rebuild the JavaScript" section in README.md still valid?

No, I'll update the README.

**Comment by sletz** [comment]
Thanks, [libfaust-wasm.data](https://github.com/ijc8/faustplayground/blob/master/libfaust-wasm.data) is not needed anymore ?

**Pull request merged**
