### PR TITLE
use faustwasm for compilation

### PR DESCRIPTION
**Pull request by Fr0stbyteR**
Updated Faust Wasm Compiler to [faustwasm](https://github.com/Fr0stbyteR/faustwasm)

May need some more tests.

### CODE REVIEW

**Comment by sletz** [comment]
Thanks a lot, I'll have a look.

**Comment by sletz** [comment]
Working great, but still some issues:
- ScriptProcessor mode is not working anymore on older Safari versions. I think this is better to keep it for now. Could it be restored?
- "Precompile" mode is not working anymore. But since this is not implemented in faust2wasm, I suggest we simply drop this feature (which was basically done to speedup loading of big patches, but does not seem mandatory). So we should remove "Small exemple precompile" and "Big exemple precompile" in the "LOAD" menu and the "Precompile (heavier)" checkbox in "SAVE" menu. Can you have a look?
- and thanks for the great work !

**Comment by sletz** [comment]
Another point: the project was built using a makefile which was calling "tsc". It does now create errors. It is still supposed to work? Or another build tool is used?

**Comment by Fr0stbyteR** [comment]
Faustwasm actually do support precompile. I updated the two examples so now they work.
I added the ScriptProcessor compilation, but I don't have a version of Safari without AudioWorklet to test...

**Comment by sletz** [comment]
Great thanks ! It works on older Safari version, but still with this message
Capture d’écran 2022-06-27 à 11 13 39
Do you see where it comes from?

**Comment by sletz** [comment]
Thanks, but the alert is still there...

**Comment by Fr0stbyteR** [comment]
Not quite sure what happened.. the code is at Main.ts l52, an error should be captured there. Can you check please? @sletz

**Comment by sletz** [comment]
Foe some reason `Utilitary.audioContext.destination.maxChannelCount = 0` on this old Safari 13.1.2 and this cause the exception that is incorrectly catched as "errorNoWebAudioAPI". This message is already there on "official" FPG, so I guess we can just ignore it and keep the code the way is behaves.

**Comment by sletz** [comment]
Was improved with https://github.com/grame-cncm/faustplayground/pull/9 and then merged, thanks!

**Pull request closed without merging**
